Add Todo-model and Todo-Service 🤙
Dualog-students/Neptun pull request #5
Opened 2019-06-18 11:42 UTC by markhilb

Add todo-model
Add todo-service
🧠

Add todo-model to represent a todo item
Add todo-service to keep a list of todo items, and provide useful
functions such as add/delete/complete todo, sort by, etc.

😬

2019-06-18 11:57 UTC, jonjohansen requested changes
Tight, but needs some fixes / explanations. 😄

2019-06-18 11:57 UTC, jonjohansen commented on src/app/app.component.ts
> +
Newlines 🔥

2019-06-18 11:57 UTC, jonjohansen commented on src/app/models/todo-model.ts
> +
Newlines 🔥

2019-06-18 11:57 UTC, jonjohansen commented on src/app/todo.service.ts
> +  constructor() {
If constructor is unused you can wrap it like:
```constructor(){ }```

2019-06-18 11:57 UTC, jonjohansen commented on src/app/todo.service.ts
> +  testAddTodo() {
Are these mock or test values? 🏭

2019-06-18 11:57 UTC, jonjohansen commented on src/app/todo.service.ts
> +
Sort logic such as sorting should be handled by the respective component and not necessarily the service.

2019-06-18 11:57 UTC, jonjohansen commented on tsconfig.json
> +    "allowSyntheticDefaultImports": true,
What does this do?

2019-06-19 06:10 UTC, Joaalslie submitted a review, later dismissed

2019-06-19 07:04 UTC, agfagerbakk submitted a review, later dismissed

2019-06-19 09:16 UTC, jonjohansen requested changes
Still a few points

2019-06-19 09:16 UTC, jonjohansen commented on tsconfig.json
> +    "allowSyntheticDefaultImports": true,
Fix this.

2019-06-19 11:14 UTC, jonjohansen approved these changes
👍

2019-06-19 11:14 UTC, merged